### ISSUE TITLE
Add self-hosting instructions to README

### ISSUE THREAD

**Issue by Tealk** [NickKaramoff/toot#17]
Is there a way to host the whole thing yourself?

**Comment by NickKaramoff** [comment]
Of course! If you fork your repository and [deploy it to Vercel via a GitHub connection](https://vercel.com/docs/git/vercel-for-github), you won't have to do anything else.

Other than that, the deployment boils down to

```sh
yarn  # to install dependencies
yarn build  # to build the website

# serve /dist folder with a static HTTP server
```

I am planning to change the architecture a bit so that one doesn't need JS to post (see #12), after that the non-Vercel deployment process may change.

Other that that, thank you for pointing out that I didn't include any instructions to self-host it 😅 I'll update the README

**Comment by Tealk** [comment]
when i try to install it i get the following message:
```
yarn
yarn install v1.22.5
[1/5] Validating package.json...
error toot@1.2.1: The engine "node" is incompatible with this module. Expected version "^14". Got "12.22.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by NickKaramoff** [comment]
Yeah, I have set the supported Node.js version to 14, so that Vercel uses that for building. Meanwhile that's no longer needed. You can try modifying or removing the `engines` field to suit your version or (recommended) use Node.js v14

**Comment by Tealk** [comment]
Thanks for the help, running :D
https://toot.rollenspiel.social/
