### ISSUE TITLE
Style toot in a more mastodon-branded way

### ISSUE THREAD

**Issue by janopae** [NickKaramoff/toot#6]
I'm really glad I found this project, I really think an instance-agnostic sharing functionality was missing and needed for mastodon.

However, I worry if people might be confused by the fact that the site is not exactly mastodon branded. Sure, it looks kind of mastodon-ish, but I'm pretty sure some people will be confused, and maybe treat it for some sort of shady phishing site, because it looks not the way joinmastadon.org looks like.

I'm pretty sure this could be fixed by some slight adjustments, that might include the straight lines that separate the header and the footer on https://joinmastodon.org/communities, and also include replacing the "toot" icon with the official mastodon logo.

@NickKaramoff What do you think about this? Would that be in line with your vision for the project?

**Comment by NickKaramoff** [comment]
Hi Jano, thank you for your suggestion! You're right — it's not obvious from the first sight that 'toot' has something to do with Mastodon. On the other side, I don't want people to think that 'toot' is a part of Mastodon (because it isn't)

I can try to think of the ways to add some Mastodon branding and references (I already do this with fonts and colours), but you should of course understand, that I can't just slap the official logo as if this is an official thing :)
